name: bus_tracker_chofer
description: Aplicación para seguimiento de buses rurales en Santiago de Chile

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  provider: ^6.0.0
  supabase_flutter: ^2.5.0 
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
